-- EnerPulse Schema V1 - compatible with PostgreSQL 15+ and H2 (PostgreSQL mode)

create table if not exists tenants (
    id bigint generated by default as identity primary key,
    name varchar(128) not null,
    code varchar(64) not null unique,
    status varchar(32) not null default 'ACTIVE',
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp
);

create table if not exists users (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null references tenants(id),
    username varchar(64) not null,
    password_hash varchar(255) not null,
    nickname varchar(128),
    mobile varchar(32),
    email varchar(128),
    status varchar(32) not null default 'ACTIVE',
    last_login_at timestamp with time zone,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    deleted_at timestamp with time zone,
    constraint uk_users_tenant_username unique (tenant_id, username)
);

create table if not exists roles (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null references tenants(id),
    name varchar(64) not null,
    code varchar(64) not null,
    description varchar(255),
    status varchar(32) not null default 'ACTIVE',
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    constraint uk_roles_tenant_code unique (tenant_id, code)
);

create table if not exists permissions (
    id bigint generated by default as identity primary key,
    code varchar(128) not null unique,
    name varchar(128) not null,
    type varchar(32) not null,
    resource varchar(255),
    action varchar(64),
    description varchar(255),
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp
);

create table if not exists user_roles (
    user_id bigint not null references users(id),
    role_id bigint not null references roles(id),
    primary key (user_id, role_id)
);

create table if not exists role_permissions (
    role_id bigint not null references roles(id),
    permission_id bigint not null references permissions(id),
    primary key (role_id, permission_id)
);

create table if not exists areas (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null references tenants(id),
    parent_id bigint references areas(id),
    area_type varchar(32) not null,
    code varchar(64) not null,
    name varchar(128) not null,
    sort_no integer not null default 0,
    status varchar(32) not null default 'ACTIVE',
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    deleted_at timestamp with time zone,
    constraint uk_areas_tenant_code unique (tenant_id, code)
);

create table if not exists dictionary_types (
    id bigint generated by default as identity primary key,
    tenant_id bigint references tenants(id),
    code varchar(64) not null,
    name varchar(128) not null,
    status varchar(32) not null default 'ACTIVE',
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    constraint uk_dict_types_tenant_code unique (tenant_id, code)
);

create table if not exists dictionary_items (
    id bigint generated by default as identity primary key,
    tenant_id bigint references tenants(id),
    type_id bigint not null references dictionary_types(id),
    code varchar(64) not null,
    name varchar(128) not null,
    unit varchar(32),
    sort_no integer not null default 0,
    status varchar(32) not null default 'ACTIVE',
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    constraint uk_dict_items unique (tenant_id, type_id, code)
);

create table if not exists gateways (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null references tenants(id),
    gateway_code varchar(64) not null,
    name varchar(128) not null,
    topic varchar(255) not null,
    server_host varchar(255) not null,
    server_port integer not null default 1883,
    report_interval integer not null default 60,
    status varchar(32) not null default 'OFFLINE',
    last_online_at timestamp with time zone,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    deleted_at timestamp with time zone,
    constraint uk_gateways_tenant_code unique (tenant_id, gateway_code),
    constraint uk_gateways_tenant_topic unique (tenant_id, topic)
);

create table if not exists devices (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null references tenants(id),
    device_code varchar(64) not null,
    name varchar(128) not null,
    gateway_id bigint references gateways(id),
    area_id bigint references areas(id),
    energy_type_id bigint,
    install_location varchar(255),
    status varchar(32) not null default 'ACTIVE',
    description varchar(500),
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    deleted_at timestamp with time zone,
    constraint uk_devices_tenant_code unique (tenant_id, device_code)
);

create table if not exists points (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null references tenants(id),
    gateway_id bigint not null references gateways(id),
    device_id bigint references devices(id),
    point_code varchar(64) not null,
    name varchar(128) not null,
    energy_type_id bigint,
    energy_item_id bigint,
    value_type varchar(32) not null,
    unit varchar(32),
    total_flag boolean not null default false,
    multiplier numeric(20,6) not null default 1,
    status varchar(32) not null default 'ACTIVE',
    description varchar(500),
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    constraint uk_points_gateway_code unique (gateway_id, point_code)
);

create table if not exists tariff_periods (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null references tenants(id),
    name varchar(64) not null,
    period_type varchar(16) not null,
    start_time time not null,
    end_time time not null,
    sort_no integer not null,
    status varchar(32) not null default 'ACTIVE',
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp
);

create table if not exists tariffs (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null references tenants(id),
    energy_type_id bigint not null,
    tariff_period_id bigint not null references tariff_periods(id),
    price numeric(18,6) not null,
    currency varchar(16) not null default 'CNY',
    effective_from timestamp with time zone not null,
    effective_to timestamp with time zone,
    status varchar(32) not null default 'ACTIVE',
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp
);

create table if not exists energy_raw_data (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    gateway_id bigint not null,
    device_id bigint,
    point_id bigint not null,
    ts timestamp with time zone not null,
    raw_value numeric(30,10) not null,
    quality varchar(32) not null default 'GOOD',
    unit varchar(32),
    message_id varchar(128),
    raw_payload jsonb,
    received_at timestamp with time zone not null default current_timestamp
);
create index if not exists idx_energy_raw_point_ts on energy_raw_data(point_id, ts desc);
create index if not exists idx_energy_raw_device_ts on energy_raw_data(device_id, ts desc);
create index if not exists idx_energy_raw_gateway_ts on energy_raw_data(gateway_id, ts desc);
create index if not exists idx_energy_raw_msg_point on energy_raw_data(message_id, point_id);

create table if not exists energy_daily (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    point_id bigint,
    device_id bigint,
    area_id bigint,
    energy_type_id bigint,
    period_date date not null,
    consumption numeric(20,6) not null default 0,
    cost numeric(20,6) not null default 0,
    data_quality varchar(32) not null default 'GOOD',
    created_at timestamp with time zone not null default current_timestamp,
    constraint uk_energy_daily unique (tenant_id, point_id, period_date)
);

create table if not exists dashboards (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null references tenants(id),
    name varchar(128) not null,
    description varchar(500),
    status varchar(32) not null default 'ACTIVE',
    created_by bigint references users(id),
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp
);

create table if not exists dashboard_widgets (
    id bigint generated by default as identity primary key,
    dashboard_id bigint not null references dashboards(id) on delete cascade,
    widget_type varchar(32) not null,
    title varchar(128),
    x integer not null default 0,
    y integer not null default 0,
    w integer not null default 4,
    h integer not null default 4,
    config_json jsonb not null default '{}',
    data_source jsonb,
    sort_no integer not null default 0,
    visible boolean not null default true
);

create table if not exists alarms (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    gateway_id bigint,
    device_id bigint,
    point_id bigint,
    alarm_code varchar(64) not null,
    alarm_type varchar(64),
    level varchar(16) not null,
    message varchar(500),
    alarm_value numeric(30,10),
    threshold numeric(30,10),
    status varchar(32) not null default 'ACTIVE',
    occurred_at timestamp with time zone not null,
    recovered_at timestamp with time zone,
    ack_by bigint references users(id),
    ack_at timestamp with time zone,
    closed_by bigint references users(id),
    closed_at timestamp with time zone,
    created_at timestamp with time zone not null default current_timestamp
);
create index if not exists idx_alarms_tenant_occurred on alarms(tenant_id, occurred_at desc);

create table if not exists notifications (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    alarm_id bigint not null references alarms(id),
    channel varchar(32) not null,
    recipient varchar(255) not null,
    status varchar(32) not null default 'PENDING',
    sent_at timestamp with time zone,
    error_message varchar(1000),
    created_at timestamp with time zone not null default current_timestamp
);

create table if not exists operation_logs (
    id bigint generated by default as identity primary key,
    tenant_id bigint,
    user_id bigint,
    action varchar(64) not null,
    module varchar(64) not null,
    target_type varchar(64),
    target_id varchar(64),
    request_id varchar(128),
    ip varchar(64),
    user_agent varchar(500),
    detail jsonb,
    created_at timestamp with time zone not null default current_timestamp
);
create index if not exists idx_operation_logs_created on operation_logs(created_at desc);
